# SVM (SUPPORT VECTOR MACHINE)

In [1]:
#There are three types of Kernal function of svm
#1.Linear SVM :use for linear data
#Non-linear data
#2.polynominal kernal function:-increase the low dimension to 

In [2]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [3]:
#Problem case study : - 
''' Basically company wants to launch their smart phone into the market ,
But they want to take a decision  whether they should keep the price more 
than 50000 or less than 50000 / - then It is the premium phone and it is less 
than 50000 than it is the normal phone .'''

#here target variable:  price_range  Whether the phone is premium means
#price_range>50000 or normal phone means price_range<50000 so that my target
#price_range=0 means <50000 and price_range=1 means >50000

' Basically company wants to launch their smart phone into the market ,\nBut they want to take a decision  whether they should keep the price more \nthan 50000 or less than 50000 / - then It is the premium phone and it is less \nthan 50000 than it is the normal phone .'

In [4]:
#df=pd.read_csv("mobile.csv")
df=pd.read_csv("bank.csv")
df.head()

age  job  marital  education  default  balance  housing  loan  contact  \
0   59    0        1          1        0     2343        1     0        2   
1   56    0        1          1        0       45        0     0        2   
2   41    9        1          1        0     1270        1     0        2   
3   55    7        1          1        0     2476        1     0        2   
4   54    0        1          2        0      184        0     0        2   

   day  month  duration  campaign  pdays  previous  poutcome  deposit  
0    5      8      1042         1     -1         0         3        1  
1    5      8      1467         1     -1         0         3        1  
2    5      8      1389         1     -1         0         3        1  
3    5      8       579         1     -1         0         3        1  
4    5      8       673         2     -1         0         3        1

In [5]:
df.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
deposit      0
dtype: int64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11162 entries, 0 to 11161
Data columns (total 17 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   age        11162 non-null  int64
 1   job        11162 non-null  int64
 2   marital    11162 non-null  int64
 3   education  11162 non-null  int64
 4   default    11162 non-null  int64
 5   balance    11162 non-null  int64
 6   housing    11162 non-null  int64
 7   loan       11162 non-null  int64
 8   contact    11162 non-null  int64
 9   day        11162 non-null  int64
 10  month      11162 non-null  int64
 11  duration   11162 non-null  int64
 12  campaign   11162 non-null  int64
 13  pdays      11162 non-null  int64
 14  previous   11162 non-null  int64
 15  poutcome   11162 non-null  int64
 16  deposit    11162 non-null  int64
dtypes: int64(17)
memory usage: 1.4 MB


In [7]:
#separate X and Y means Input and Output(Labelled means target)
X=df.drop("deposit",axis=1) #input features
Y=df["deposit"] #output means target which want to predict

In [8]:
#Train_Test_Split:70% & 30%
from sklearn.model_selection import train_test_split
#split our dataset in train test of 70% & 30%
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.3,random_state=1)

In [9]:
from sklearn.preprocessing import StandardScaler

In [10]:
#create object of StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train) #training data
X_test=ss.transform(X_test) #testing data

In [11]:
#create a function
def create_model(model):
    model.fit(X_train,Y_train)
    Y_pred=model.predict(X_test)
    print(classification_report(Y_test,Y_pred))
    print(confusion_matrix(Y_test,Y_pred))
    return model

In [12]:
#basline model: take logistic regression
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [13]:
#create object of Logistic Regression
lr=LogisticRegression()

In [14]:
#call th function
lr=create_model(lr)

              precision    recall  f1-score   support

           0       0.80      0.82      0.81      1760
           1       0.79      0.77      0.78      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.80      0.80      0.80      3349

[[1441  319]
 [ 359 1230]]


In [15]:
#Support Vector Machine:-
#use SVM :-support vector machine :-this is a classification supervised learning algo
'''there are various kernel functions:
1.Linear kernel function (use linear separated data)
2.polynominal kernel function (non-linear)
3.radial basis kernel function (non-linearly)'''

'there are various kernel functions:\n1.Linear kernel function (use linear separated data)\n2.polynominal kernel function (non-linear)\n3.radial basis kernel function (non-linearly)'

In [16]:
#Linear Kernel function means data is linearly separately
#use inbuilt class Linear SVC which define in svm inbuilt package
from sklearn.svm import LinearSVC
#support vector classifier : SVC
#create the object of LinearSVC class
svc=LinearSVC(random_state=1) #by default hard margin means no add any error on trading time

In [17]:
#call function
svc=create_model(svc)

              precision    recall  f1-score   support

           0       0.80      0.82      0.81      1760
           1       0.79      0.77      0.78      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.80      0.80      0.80      3349

[[1444  316]
 [ 364 1225]]


In [18]:
#Score not bad but try best its better
#apply soft margin means add extremely error on training time
#create the object of inbuilt class LinearSVC and passing parameter C
#for error
svc1=LinearSVC(random_state=1,C=0.3) #soft meargin
#range of C :0.01 to 0.9 & C is used to add error on training data
#soft margin mean to reduce overfitting situation and remove the outlier

In [19]:
#call function
svc1=create_model(svc1)

              precision    recall  f1-score   support

           0       0.80      0.82      0.81      1760
           1       0.79      0.77      0.78      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.80      0.80      0.80      3349

[[1444  316]
 [ 364 1225]]


In [20]:
#Here if add external error on runtime but no changes in score means no 
#effect on score
#means we have data is non-linear data  , not linear dataset 
#So we will use polynomial kernel function means increase the dimension means
#to converts low dimension data into high dimension means if plot 1D then
#converting into 2D dimension and so on.

In [21]:
#2.polynominal Kernel function of svm so, use inbuilt class SVC
from sklearn.svm import SVC
#SVC inuilt class for non-linear data

In [22]:
#create the object of SVC class
poly_svc=SVC(random_state=1,kernel="poly")

In [23]:
#call the function
#this is non-linear data
poly_svc=create_model(poly_svc)

              precision    recall  f1-score   support

           0       0.82      0.81      0.81      1760
           1       0.79      0.80      0.80      1589

    accuracy                           0.80      3349
   macro avg       0.80      0.80      0.80      3349
weighted avg       0.81      0.80      0.80      3349

[[1417  343]
 [ 311 1278]]


In [24]:
#create the object of SVC class
r_svc=SVC(random_state=1,kernel="rbf")
#rbf means radial basis function

In [25]:
#call the function
#this is non-linear data
r_svc=create_model(r_svc)

              precision    recall  f1-score   support

           0       0.84      0.80      0.82      1760
           1       0.79      0.84      0.81      1589

    accuracy                           0.82      3349
   macro avg       0.82      0.82      0.82      3349
weighted avg       0.82      0.82      0.82      3349

[[1407  353]
 [ 262 1327]]
